title: Aleksandar Anžel
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aleksandar Anžel # add your name
author-img: profile-small.jpg # add your photo
about-author: A recent graduate of The Faculty of Mathematics, University of Belgrade with a Master's degree in Mathematics, module Computer Science and Informatics. Interested into applying Machine Learning in Computational and Systems Biology. # add description
social-twitter: AleksandarAnzel # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: AAnzel # add your Github handle
social-linkedin: aanzel # add your Linkedin handle
social-email: aleksandar.anzel@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
